server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-port: ${server.port}


spring:
  application:
    name: eureka
  cloud:
    config:
      uri: http://localhost:${server.port}

