zuul:
  routes:
    index:
      path: /index/**
      serviceId: CONSUMER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/
spring:
  application:
    name: zuul
server:
  port: 7000


